version: '3.9'

services:
  backend:
    image: backend
    ports:
      - 5000:5000
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      DB_USER: ${DB_USER_PG}
      DB_PASSWORD: ${DB_PASSWORD_PG}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: exchange_rates
    depends_on:
      - postgres
    networks:
      - my_network

  frontend:
    image: frontend
    ports:
      - 3000:3000
    command: npm start
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      REACT_APP_API_URL: http://backend:5000
      CHOKIDAR_USEPOLLING: true
    networks:
      - my_network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER_PG}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PG}
      POSTGRES_DB: exchange_rates
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network: